### ISSUE TITLE
Error on launching asset file

### ISSUE THREAD

**Issue by Taiwofolu** [eaxum/nagato#8]
I get this error in th console whenever I try to launch any asset task

`Python: Traceback (most recent call last):
  File "C:\Users\itachi\Eaxum\Softwares\Blender_Foundation\Blender Add-ons\scripts\addons\nagato\kitsu.py", line 406, in execute
    initialize_file(file_data=task_file_data)
  File "C:\Users\itachi\Eaxum\Softwares\Blender_Foundation\Blender Add-ons\scripts\addons\nagato\kitsu.py", line 95, in initialize_file
    scene['task_file_data'] = file_data
TypeError: 'NoneType' object does not support item assignment

location: <unknown location>:-1`

**Comment by Aderemi-Adesada** [comment]
fix in v0.2.9 https://github.com/eaxum/nagato/releases/tag/v0.2.9
